### ISSUE TITLE
[very low priority] \drawAngleWithSides skips angle sides directed at 3 o'clock

### ISSUE THREAD

**Issue by MarcinCiura** [jemmybutton/byrne-euclid#66] opened 2022-02-11 15:26 UTC
The second angle of the second item (`DHF`) is only drawn with one side:
[drawAngleWithSides-example.pdf](https://github.com/jemmybutton/byrne-euclid/files/8049628/drawAngleWithSides-example.pdf)
There is an easy workaround: do not make the side horizontal. Source code follows:
```
\setuppapersize[A4]

\input preamble.tex
\input preamble_be.tex

\starttext
\defineNewPicture{
pair A, B, C, D, E, F, G, H;
A := (0, 0);
B := (3u, -1u);
C := (0, -2u);   % WORKAROUND: 
D := (3u, -2u);  % make CD non-horizontal
E := (1.2u, 1u);
F := (1.8u, -3.5u);
G := (E--F) intersectionpoint (A--B);
H := (E--F) intersectionpoint (C--D);
byAngleDefine(A, G, E, byred, 0);
byAngleDefine(C, H, G, byred, 1);
byAngleDefine(B, G, E, bygrey, 0);
byAngleDefine(D, H, G, bygrey, 1);
byAngleDefine(B, G, H, byblue, 0);
byAngleDefine(D, H, F, byblue, 1);
byAngleDefine(A, G, H, byyellow, 0);
byAngleDefine(C, H, F, byyellow, 1);
draw byNamedAngleResized();
draw byLine(A, B, byblue, 0, 0);
draw byLine(C, H, byblue, 0, 0);
draw byLine(H, D, byblue, 0, 0);
draw byLine(E, G, byblack, 0, 0);
draw byLine(G, H, byblack, 0, 0);
draw byLine(H, F, byblack, 0, 0);
byLineDefine(C, D, byblue, 0, 0);
byLineDefine(E, F, byblack, 0, 0);
draw byLabelLine(0)(AB, CD, EF);
draw byLabelPoint(G)(45, 1);
draw byLabelPoint(H)(45, 1);
}
\drawCurrentPictureInMargin

Odcinek przecinający dwa inne odcinki
tworzy z~nimi kąty o~następujących nazwach:
\startitemize[1]
\item kąty \drawAngle{AGE} i~\drawAngleWithSides{CHG} to przykład
  \emph{kąta zewnętrznego} i~\emph{odpowiadającego mu kąta wewnętrznego};
\item kąty \drawAngle{AGE} i~\drawAngleWithSides{DHF} to przykład \emph{naprzemianległych kątów zewnętrznych};
\item kąty \drawAngle{AGH} i~\drawAngleWithSides{DHG} to przykład \emph{naprzemianległych kątów wewnętrznych};
\item kąty \drawAngle{AGE} i~\drawAngleWithSides{CHF} to przykład \emph{jednostronnych kątów zewnętrznych};
\item kąty \drawAngle{AGH} i~\drawAngleWithSides{CHG} to przykład \emph{jednostronnych kątów wewnętrznych}.
\stopitemize
\stoptext
```

**Comment by jemmybutton** [comment] 2022-02-11 18:17
@MarcinCiura This is a bug in a function responsible for producing angle arcs. Should be fixed by [this](https://github.com/jemmybutton/byrne-euclid/commit/1c8df90499013b793aced72b4ef349257877f3c3#diff-e9b4829fa2b1a5340edcb2b3b2b6d0eeddbad1d3d4ed2e64a026b290c3b4dd15R2507). Thanks for noticing!

**Comment by jemmybutton** [comment] 2022-02-12 12:43
I guess, I can close this issue for now, since the provided example seems to work as intended.
[angletest.pdf](https://github.com/jemmybutton/byrne-euclid/files/8053390/angletest.pdf)

**Closed by jemmybutton** 2022-02-12 12:43 UTC
Labels: bug
